version: '3'

services:
  suitecrm:
    build: ./
    image: suitecrm:latest
    networks:
      - suitecrm_net
    volumes:
      #SuiteCRM Application Folder
      - ./www:/var/www/html
      #SuiteCRM Log Folder
      - ./logs/SuiteCRM:/var/www/html/SuiteCRM/logs
      - ./logs/SuiteCRM_Core/suitecrm.log:/var/www/SuiteCRM/public/legacy/suitecrm.log
      #PHP config
      - ./docker/config/php/php.ini:/etc/php/8.2/apache2/php.ini
      #APACHE config
      - ./docker/config/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/config/apache/sites.conf:/etc/apache2/sites-enabled/sites.conf
      - ./docker/config/apache/apache-selfsigned.crt:/etc/ssl/certs/apache-selfsigned.crt
      - ./docker/config/apache/apache-selfsigned.key:/etc/ssl/private/apache-selfsigned.key
      #APACHE Log Folder
      - ./logs/apache:/var/log/apache2/  
      #PHP Log Folder
      - ./logs/php:/var/log/php/
    env_file:
      - environment/sample.env
    ports:
      - "4000:80"
      - "8081:443"
    restart: on-failure
    labels:
      - me.titmus.authors="jon@titmus.me"

  mysql_crm:
    image: mysql:5.7

    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_PASSWORD=suitecrm
      - MYSQL_DATABASE=suitecrm
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - suitecrm_net
    restart: on-failure
 
networks:
    suitecrm_net:
        driver: bridge
